
#  Task 4 (v2): Multi-Stage Approximate Dynamic Programming
#
#  ADP ARCHITECTURE OVERVIEW
#  ─────────────────────
#  MULTI-STAGE deployment MILP.
#  The value function approximation (VFA) and training
#
#    V̂_t(s ; θ_t) = θ_t ᵀ φ(s)      [linear in weights θ, nonlinear in s OK]


#  v1 (1-step):   min  c_t(a_t)  +  θ_{t+1}ᵀ φ(s̃_{t+1})           
#                                                                     
#   v2 (L-step):   min  Σ_{τ=0}^{L-1} c_{t+τ}(a_{t+τ})              
#                           + θ_{t+L}ᵀ φ(s̃_{t+L})                      
                                                                  
#  The first L stages are optimised EXPLICITLY with full dynamics.   
#   The VFA captures all costs BEYOND the lookahead horizon.          


#
#  MILP structure at deployment
#  ────────────────────────────
#  Decision variables:   p1[τ], p2[τ], v[τ]   for τ = 0, …, L-1
#  State variables:      T1[τ], T2[τ], H[τ], vc[τ]   for τ = 0, …, L
#                        (τ=0 is the current observed state, fixed)
#  Auxiliary variables:  z1[L], z2[L]  for the VFA cold-risk features
#
#  Stochastic inputs (price, occupancy) are replaced by their EXPECTED
#  values at each future stage — the same certainty-equivalent approach
#  used in the 1-step version, just extended over more steps.

# imports
import os
import sys
import numpy as np
import pyomo.environ as pyo
from SystemCharacteristics import get_fixed_data

try:
    _DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    _DIR = os.getcwd()
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)


# ═══════════════════════════════════════════════════════════════════════
# SECTION 1 — CONSTANTS & SYSTEM PARAMETERS
# ═══════════════════════════════════════════════════════════════════════

PARAMS   = get_fixed_data()
T_SLOTS  = int(PARAMS['num_timeslots'])   # 10 hours

# VFA hyperparameters
# N_SCENARIOS is set lower than v1 (50 vs 200) because on-policy training is
# more data-efficient: each trajectory is generated by the deployment policy,
# so there is no off-policy mismatch to overcome.  50 scenarios × 10 steps
# gives 500 data points for a 12-feature ridge regression — statistically solid.
# With Gurobi (100× faster than HiGHS), 200 scenarios is feasible in <5 s.
N_FEATURES   = 12
N_SCENARIOS  = 2000    # training scenarios (used by offline training script)
N_ITER       = 5
RIDGE_ALPHA  = 1e-2




# Multi-stage lookahead depth
# L=5: explicit optimisation over 5 stages + VFA terminal for remaining 5
LOOKAHEAD_STEPS = 3

# Epsilon margin: added to T_LOW inside the MILP to create a safety buffer
# against forecast error. Prevents accidental overrule trigger from
# certainty-equivalent forecasts being slightly off.
EPSILON_TEMP = 0.5   # °C buffer above T_LOW




# ═══════════════════════════════════════════════════════════════════════
# SECTION 2 — FEATURE FUNCTION  φ(s) 


def compute_features(state):
    """
    Returns φ(s) ∈ ℝ^12.  Same feature map as the 1-step ADP.

    Feature index  |  φ_k(s)                        |  Why it matters
    ───────────────┼─────────────────────────────────┼──────────────────────────
     0             |  1   (bias)                     |  baseline cost offset
     1             |  T1 / 25                        |  room 1 temp
     2             |  T2 / 25                        |  room 2 temp
     3             |  H  / 50                        |  humidity
     4             |  λ  / 6                         |  current price
     5             |  λ_prev / 6                     |  price momentum
     6             |  κ1 / 35                        |  occupancy room 1
     7             |  κ2 / 35                        |  occupancy room 2
     8             |  t  / 10                        |  time-to-go
     9             |  c_vent / 3                     |  ventilation lock-in
    10             |  max(0, T_low − T1) / 5         |  cold risk r1
    11             |  max(0, T_low − T2) / 5         |  cold risk r2
    """
    T_LOW = PARAMS['temp_min_comfort_threshold']
    phi = np.array([
        1.0,
        state['T1']             / 25.0,
        state['T2']             / 25.0,
        state['H']              / 50.0,
        state['price_t']        / 6.0,
        state['price_previous'] / 6.0,
        state['Occ1']           / 35.0,
        state['Occ2']           / 35.0,
        state['current_time']   / float(T_SLOTS),
        min(state['vent_counter'], 3) / 3.0,
        max(0.0, T_LOW - state['T1']) / 5.0,
        max(0.0, T_LOW - state['T2']) / 5.0,
    ], dtype=float)
    return phi


# ═══════════════════════════════════════════════════════════════════════
# SECTION 3 — STOCHASTIC PROCESS MODELS
# ═══════════════════════════════════════════════════════════════════════

def _sample_next_price(price_t, price_prev):
    mean_price         = 4.0
    reversion_strength = 0.12
    next_p = (price_t
              + 0.6 * (price_t - price_prev)
              + reversion_strength * (mean_price - price_t)
              + np.random.normal(0, 0.5))
    if next_p < 0 and np.random.rand() > 0.2:
        next_p = np.random.uniform(0, mean_price * 0.3)
    return float(np.clip(next_p, 0.0, 12.0))


def _expected_next_price(price_t, price_prev):
    mean_price         = 4.0
    reversion_strength = 0.12
    exp_p = (price_t
             + 0.6 * (price_t - price_prev)
             + reversion_strength * (mean_price - price_t))
    return float(np.clip(exp_p, 0.0, 12.0))


def _sample_next_occupancy(occ1, occ2):
    mean_r1, mean_r2 = 35.0, 25.0
    rev, coupling    = 0.25, 0.10
    r1 = occ1 + rev*(mean_r1-occ1) + coupling*(occ2-occ1) + np.random.normal(0, 3.0)
    r2 = occ2 + rev*(mean_r2-occ2) + coupling*(occ1-occ2) + np.random.normal(0, 2.5)
    return float(np.clip(r1, 20, 50)), float(np.clip(r2, 10, 30))


def _expected_next_occupancy(occ1, occ2):
    mean_r1, mean_r2 = 35.0, 25.0
    rev, coupling    = 0.25, 0.10
    r1 = occ1 + rev*(mean_r1-occ1) + coupling*(occ2-occ1)
    r2 = occ2 + rev*(mean_r2-occ2) + coupling*(occ1-occ2)
    return float(np.clip(r1, 20, 50)), float(np.clip(r2, 10, 30))


# ═══════════════════════════════════════════════════════════════════════
# SECTION 4 — SYSTEM DYNAMICS  
# ═══════════════════════════════════════════════════════════════════════

def _apply_overrule(state, action):
    d  = PARAMS
    p1 = action['HeatPowerRoom1']
    p2 = action['HeatPowerRoom2']
    v  = action['VentilationON']

    if state['H'] > d['humidity_threshold']:
        v = 1
    elif state['vent_counter'] > 0 and state['vent_counter'] < d['vent_min_up_time']:
        v = 1

    if state['T1'] > d['temp_max_comfort_threshold']:
        p1 = 0.0
    elif state['low_override_r1'] == 1:
        p1 = d['heating_max_power']

    if state['T2'] > d['temp_max_comfort_threshold']:
        p2 = 0.0
    elif state['low_override_r2'] == 1:
        p2 = d['heating_max_power']

    return {'HeatPowerRoom1': p1, 'HeatPowerRoom2': p2, 'VentilationON': v}


def _step(state, action, occ1_next, occ2_next, price_next):
    d  = PARAMS
    t  = state['current_time']
    p1 = float(action['HeatPowerRoom1'])
    p2 = float(action['HeatPowerRoom2'])
    v  = float(action['VentilationON'])

    T_out = d['outdoor_temperature'][t]

    T1_next = (state['T1']
               + d['heat_exchange_coeff']      * (state['T2'] - state['T1'])
               + d['thermal_loss_coeff']       * (T_out - state['T1'])
               + d['heating_efficiency_coeff'] * p1
               - d['heat_vent_coeff']          * v
               + d['heat_occupancy_coeff']     * state['Occ1'])

    T2_next = (state['T2']
               + d['heat_exchange_coeff']      * (state['T1'] - state['T2'])
               + d['thermal_loss_coeff']       * (T_out - state['T2'])
               + d['heating_efficiency_coeff'] * p2
               - d['heat_vent_coeff']          * v
               + d['heat_occupancy_coeff']     * state['Occ2'])

    H_next = (state['H']
              + d['humidity_occupancy_coeff'] * (state['Occ1'] + state['Occ2'])
              - d['humidity_vent_coeff']      * v)

    vc_next = (state['vent_counter'] + 1) if v >= 0.5 else 0

    lo_r1_next = int(
        T1_next <= d['temp_min_comfort_threshold'] or
        (state['low_override_r1'] == 1 and T1_next < d['temp_OK_threshold'])
    )
    lo_r2_next = int(
        T2_next <= d['temp_min_comfort_threshold'] or
        (state['low_override_r2'] == 1 and T2_next < d['temp_OK_threshold'])
    )

    stage_cost = state['price_t'] * (p1 + p2 + d['ventilation_power'] * v)

    next_state = {
        'T1':             T1_next,
        'T2':             T2_next,
        'H':              H_next,
        'Occ1':           occ1_next,
        'Occ2':           occ2_next,
        'price_t':        price_next,
        'price_previous': state['price_t'],
        'vent_counter':   vc_next,
        'low_override_r1': lo_r1_next,
        'low_override_r2': lo_r2_next,
        'current_time':   t + 1,
    }
    return next_state, stage_cost


def _greedy_action(state):
    d  = PARAMS
    v  = 1 if state['H'] > d['humidity_threshold'] * 0.75 else 0
    p1 = d['heating_max_power'] * 0.5
    p2 = d['heating_max_power'] * 0.5
    return _apply_overrule(state, {'HeatPowerRoom1': p1,
                                   'HeatPowerRoom2': p2,
                                   'VentilationON':  v})


# ═══════════════════════════════════════════════════════════════════════
# SECTION 5 — TRAINING  
# ═══════════════════════════════════════════════════════════════════════

#  Forward-backward approximate backward induction.
#  The training produces per-time-step weight vectors θ_t that are used
#  by BOTH the 1-step and multi-stage deployment MILPs.

def _sample_training_day():
    price0 = np.random.uniform(2.0, 8.0)
    occ10  = np.random.uniform(25.0, 35.0)
    occ20  = np.random.uniform(15.0, 25.0)

    prices = [price0]
    occ1s  = [occ10]
    occ2s  = [occ20]

    for _ in range(T_SLOTS - 1):
        p_prev = prices[-2] if len(prices) > 1 else 6.0
        prices.append(_sample_next_price(prices[-1], p_prev))
        o1, o2 = _sample_next_occupancy(occ1s[-1], occ2s[-1])
        occ1s.append(o1)
        occ2s.append(o2)

    return prices, occ1s, occ2s


def _make_initial_state(prices, occ1s, occ2s):
    d = PARAMS
    T1_init = np.random.uniform(16.0, 24.0)
    T2_init = np.random.uniform(16.0, 24.0)
    H_init  = np.random.uniform(30.0, 60.0)
    return {
        'T1':             T1_init,
        'T2':             T2_init,
        'H':              H_init,
        'Occ1':           occ1s[0],
        'Occ2':           occ2s[0],
        'price_t':        prices[0],
        'price_previous': 4.0,
        'vent_counter':   0,
        'low_override_r1': int(T1_init <= d['temp_min_comfort_threshold']),
        'low_override_r2': int(T2_init <= d['temp_min_comfort_threshold']),
        'current_time':   0,
    }


def _get_solver():
    """Return the first available MILP solver (Gurobi → HiGHS → CBC → GLPK)."""
    for name in ('gurobi', 'highs', 'cbc', 'glpk'):
        s = pyo.SolverFactory(name)
        if s.available():
            return s
    raise RuntimeError("No MILP solver found. Install Gurobi, HiGHS, CBC, or GLPK.")


def _solve_1step_MILP(state, theta_next):
    """
    1-step lookahead MILP — used ONLY during training forward passes
    (iterations 1+) to generate better trajectories.
    Identical to v1's _solve_lookahead_MILP.
    """
    d   = PARAMS
    t   = int(state['current_time'])
    T1        = float(state['T1'])
    T2        = float(state['T2'])
    H         = float(state['H'])
    lam       = float(state['price_t'])
    lam_prev  = float(state['price_previous'])
    Occ1      = float(state['Occ1'])
    Occ2      = float(state['Occ2'])
    vc        = int(state['vent_counter'])
    lo_r1     = int(state['low_override_r1'])
    lo_r2     = int(state['low_override_r2'])
    T_out_t   = float(d['outdoor_temperature'][t])
    T_LOW     = float(d['temp_min_comfort_threshold']) + EPSILON_TEMP  # epsilon buffer

    lam_next_exp                   = _expected_next_price(lam, lam_prev)
    occ1_next_exp, occ2_next_exp   = _expected_next_occupancy(Occ1, Occ2)

    a  = d['heat_exchange_coeff']
    b_ = d['thermal_loss_coeff']
    g  = d['heating_efficiency_coeff']
    c_ = d['heat_vent_coeff']
    e  = d['heat_occupancy_coeff']
    eh = d['humidity_occupancy_coeff']
    hv = d['humidity_vent_coeff']
    vc_next_coef = float(min(vc + 1, 3))

    T1_const = T1 + a*(T2-T1) + b_*(T_out_t-T1) + e*Occ1
    T2_const = T2 + a*(T1-T2) + b_*(T_out_t-T2) + e*Occ2
    H_const  = H  + eh*(Occ1+Occ2)

    m = pyo.ConcreteModel()
    m.p1 = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, d['heating_max_power']))
    m.p2 = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, d['heating_max_power']))
    m.v  = pyo.Var(domain=pyo.Binary)
    _Z_MAX = 1.0
    m.z1 = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, _Z_MAX))
    m.z2 = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, _Z_MAX))

    def T1_next(m): return T1_const + g*m.p1 - c_*m.v
    def T2_next(m): return T2_const + g*m.p2 - c_*m.v
    def H_next(m):  return H_const  - hv*m.v

    def vfa(m):
        th = theta_next
        t_next = t + 1
        return (
            th[0]  * 1.0
          + th[1]  * T1_next(m)            / 25.0
          + th[2]  * T2_next(m)            / 25.0
          + th[3]  * H_next(m)             / 50.0
          + th[4]  * lam_next_exp          / 6.0
          + th[5]  * lam                   / 6.0
          + th[6]  * occ1_next_exp         / 35.0
          + th[7]  * occ2_next_exp         / 35.0
          + th[8]  * t_next                / float(T_SLOTS)
          + th[9]  * (vc_next_coef * m.v)  / 3.0
          + th[10] * m.z1
          + th[11] * m.z2
        )

    m.obj = pyo.Objective(
        expr = lam * (m.p1 + m.p2 + d['ventilation_power'] * m.v) + vfa(m),
        sense = pyo.minimize
    )

    m.z1_nonneg = pyo.Constraint(expr = m.z1 >= 0.0)
    m.z1_cold   = pyo.Constraint(expr = m.z1 >= (T_LOW - T1_next(m)) / 5.0)
    m.z2_nonneg = pyo.Constraint(expr = m.z2 >= 0.0)
    m.z2_cold   = pyo.Constraint(expr = m.z2 >= (T_LOW - T2_next(m)) / 5.0)

    if 0 < vc < d['vent_min_up_time']:
        m.vent_inertia = pyo.Constraint(expr = m.v == 1)
    if H > d['humidity_threshold']:
        m.hum_overrule = pyo.Constraint(expr = m.v == 1)

    if T1 > d['temp_max_comfort_threshold']:
        m.p1_hi = pyo.Constraint(expr = m.p1 == 0.0)
    elif lo_r1 == 1:
        m.p1_lo = pyo.Constraint(expr = m.p1 == d['heating_max_power'])

    if T2 > d['temp_max_comfort_threshold']:
        m.p2_hi = pyo.Constraint(expr = m.p2 == 0.0)
    elif lo_r2 == 1:
        m.p2_lo = pyo.Constraint(expr = m.p2 == d['heating_max_power'])

    solver = _get_solver()
    result = solver.solve(m, tee=False)
    ok = (result.solver.termination_condition == pyo.TerminationCondition.optimal)
    if not ok:
        return _greedy_action(state)

    return {
        'HeatPowerRoom1': float(np.clip(pyo.value(m.p1), 0.0, d['heating_max_power'])),
        'HeatPowerRoom2': float(np.clip(pyo.value(m.p2), 0.0, d['heating_max_power'])),
        'VentilationON':  int(round(float(pyo.value(m.v)))),
    }


def train_ADP(n_scenarios=N_SCENARIOS, n_iter=N_ITER, ridge=RIDGE_ALPHA,
              verbose=True):
    """
    Train the ADP value function weights using on-policy forward passes.

    KEY DIFFERENCE from v1:
      Iterations 1+  use the MULTI-STAGE MILP (not the 1-step MILP) to generate
      forward-pass trajectories.  This makes training on-policy with respect to
      the deployment policy, so the value function weights θ_t are fitted to
      states and costs that the multi-stage agent actually encounters.

    The backward pass (Bellman targets + ridge regression) is identical to v1.
    Returns theta_list[t] for t = 0 … T_SLOTS-1.
    """
    np.random.seed(42)
    if verbose:
        print(f"[ADP-MS] Training: {n_scenarios} scenarios × {n_iter} iterations …")

    theta_list = [np.zeros(N_FEATURES) for _ in range(T_SLOTS)]

    for iteration in range(n_iter):
        trajectories = []
        for _ in range(n_scenarios):
            prices, occ1s, occ2s = _sample_training_day()
            state = _make_initial_state(prices, occ1s, occ2s)
            traj  = []

            for t in range(T_SLOTS):
                if iteration == 0:
                    # Iteration 0: greedy baseline seeds the state space cheaply
                    action = _greedy_action(state)
                else:
                    # Iterations 1+: use the MULTI-STAGE MILP so trajectories
                    # are generated by the same policy that will be deployed.
                
                    action = _solve_multistage_MILP(state, theta_list, LOOKAHEAD_STEPS)
                    action = _apply_overrule(state, action)

                occ1_next  = occ1s[t + 1]  if t + 1 < T_SLOTS else occ1s[-1]
                occ2_next  = occ2s[t + 1]  if t + 1 < T_SLOTS else occ2s[-1]
                price_next = prices[t + 1] if t + 1 < T_SLOTS else prices[-1]

                next_state, cost = _step(state, action,
                                         occ1_next, occ2_next, price_next)
                traj.append((state.copy(), action.copy(), cost, next_state.copy()))
                state = next_state

            trajectories.append(traj)

        for t in range(T_SLOTS - 1, -1, -1):
            Phi = np.zeros((n_scenarios, N_FEATURES))
            y   = np.zeros(n_scenarios)

            for j, traj in enumerate(trajectories):
                state_t, _, cost_t, state_t1 = traj[t]
                Phi[j] = compute_features(state_t)

                if t == T_SLOTS - 1:
                    y[j] = cost_t
                else:
                    V_next = theta_list[t + 1] @ compute_features(state_t1)
                    y[j]   = cost_t + V_next

            A             = Phi.T @ Phi + ridge * np.eye(N_FEATURES)
            b             = Phi.T @ y
            theta_list[t] = np.linalg.solve(A, b)

        if verbose:
            s_ref = _make_initial_state([4.0]*T_SLOTS,
                                        [30.0]*T_SLOTS,
                                        [20.0]*T_SLOTS)
            V0 = theta_list[0] @ compute_features(s_ref)
            print(f"  Iteration {iteration+1}/{n_iter}  |  "
                  f"V̂_0(s_ref) = {V0:.3f} €")

    if verbose:
        print("[ADP-MS] Training complete.")
    return theta_list


# ══════════════════════════════════════════════════
# SECTION 6 — DEPLOYMENT: MULTI-STAGE LOOKAHEAD MILP 
# ══════════════════════════════════════════════════

#  Given current state s_t and pre-trained weights θ_{t+1}, …, θ_{t+L},
#  solve a deterministic L-step lookahead MILP:
#
#    min  Σ_{τ=0}^{L-1}  λ_{t+τ} · (p1_τ + p2_τ + P_vent · v_τ)
#         + θ_{t+L}ᵀ φ(s̃_{t+L})          ← VFA terminal value
#
#  State evolution across stages uses the EXACT system dynamics.
#  Stochastic inputs (price, occupancy) at future stages are replaced
#  by their conditional expectations (certainty equivalent).
#
#  This MILP has 3·L decision variables (p1, p2, v per stage), plus
#  state-tracking and auxiliary variables.  For L=3 this is 9 decision
#  vars + ~20 auxiliary vars — still tiny and solves in < 1 second.

def _solve_multistage_MILP(state, theta_list, L):
    """
    Solve the L-step lookahead MILP.

    Parameters
    ----------
    state      : dict — current environment state
    theta_list : list of arrays — VFA weights for all time steps
    L          : int  — number of lookahead stages

    Returns
    -------
    action dict (here-and-now decision at τ=0 only)
    """
    d     = PARAMS
    t0    = int(state['current_time'])
    T_LOW_REAL = float(d['temp_min_comfort_threshold'])   # 18.0 — real threshold
    T_LOW = T_LOW_REAL + EPSILON_TEMP                     # 18.5 — MILP planning threshold
    P_MAX = float(d['heating_max_power'])

    # Dynamics coefficients
    a_ex = d['heat_exchange_coeff']        # 0.6  inter-room exchange
    b_tl = d['thermal_loss_coeff']         # 0.1  outdoor thermal loss
    g_he = d['heating_efficiency_coeff']   # 1.0  heater → temp
    c_vc = d['heat_vent_coeff']            # 0.7  ventilation cooling
    e_oc = d['heat_occupancy_coeff']       # 0.02 occupancy heating
    eh   = d['humidity_occupancy_coeff']   # 0.18 occupancy → humidity
    hv   = d['humidity_vent_coeff']        # 15.0 ventilation → humidity
    P_V  = d['ventilation_power']          # 2.0  vent power consumption
    U_V  = int(d['vent_min_up_time'])      # 3    min consecutive hours

    # ── Pre-compute expected stochastic trajectories over L steps ──────
    #
    #  Stage τ=0 uses the observed state.  For τ=1,…,L we propagate
    #  the conditional expectation of price and occupancy.

    exp_price    = [float(state['price_t'])]
    exp_price_prev = [float(state['price_previous'])]
    exp_occ1     = [float(state['Occ1'])]
    exp_occ2     = [float(state['Occ2'])]

    for tau in range(1, L + 1):
        p_next = _expected_next_price(exp_price[-1], exp_price_prev[-1])
        o1_next, o2_next = _expected_next_occupancy(exp_occ1[-1], exp_occ2[-1])
        exp_price_prev.append(exp_price[-1])
        exp_price.append(p_next)
        exp_occ1.append(o1_next)
        exp_occ2.append(o2_next)

    # Outdoor temperature at each stage (deterministic, known)
    T_out = []
    for tau in range(L):
        tidx = t0 + tau
        if tidx < len(d['outdoor_temperature']):
            T_out.append(float(d['outdoor_temperature'][tidx]))
        else:
            T_out.append(float(d['outdoor_temperature'][-1]))

    # Build the Pyomo model
    m = pyo.ConcreteModel()

    stages = list(range(L))          # τ = 0, 1, …, L-1  (decision stages)
    states = list(range(L + 1))      # τ = 0, 1, …, L    (state stages)

    # Decision variables at each stage
    m.p1 = pyo.Var(stages, domain=pyo.NonNegativeReals, bounds=(0.0, P_MAX))
    m.p2 = pyo.Var(stages, domain=pyo.NonNegativeReals, bounds=(0.0, P_MAX))
    m.v  = pyo.Var(stages, domain=pyo.Binary)

    # State variables at each state-stage
    m.T1 = pyo.Var(states, bounds=(5.0, 40.0))
    m.T2 = pyo.Var(states, bounds=(5.0, 40.0))
    m.H  = pyo.Var(states, bounds=(0.0, 200.0))

    # Ventilation counter — integer, tracks consecutive hours ON
    # We model this as a continuous variable bounded [0, 10] and use
    # the piecewise logic from the dynamics.  For the MILP we track
    # it linearly:  vc[τ+1] = (vc[τ]+1)·v[τ]  which we linearise.
    m.vc = pyo.Var(states, domain=pyo.NonNegativeReals, bounds=(0.0, float(T_SLOTS)))

    # Auxiliary for linearising vc[τ+1] = (vc[τ]+1) · v[τ]
    # We introduce w[τ] = vc[τ] · v[τ]  (McCormick linearisation)
    m.w  = pyo.Var(stages, domain=pyo.NonNegativeReals, bounds=(0.0, float(T_SLOTS)))

    # Terminal VFA cold-risk auxiliary variables
    _Z_MAX = 1.0
    m.z1 = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, _Z_MAX))
    m.z2 = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, _Z_MAX))

    # ── Overrule-tracking variables for future stages ─────────────────
    #
    #  The environment's overrule controller enforces:
    #    lo_r(τ)=1  →  p_r(τ) = P_MAX       (heating forced to max)
    #    H(τ) > H_THR  →  v(τ) = 1          (ventilation forced on)
    #
    #  lo_r(τ) = 1  iff  T_r(τ) ≤ T_LOW                    [cold trigger]
    #                 OR  (lo_r(τ-1)=1 AND T_r(τ) < T_OK)   [hysteresis]
    #
    #  Linearised with big-M indicator constraints.  Variables:
    #    cold_r(τ)     ≡ [T_r(τ) ≤ T_LOW]
    #    not_warm_r(τ) ≡ [T_r(τ) < T_OK]
    #    bc_r(τ)       = AND(lo_r(τ−1), not_warm_r(τ))
    #    lo_r(τ)       = OR(cold_r(τ), bc_r(τ))
    #    hum_hi(τ)     ≡ [H(τ) > H_THR]
    #
    #  Total new binaries:  ~(6·L + L-1) per room pair ≈ 20 for L=3.
    #  Gurobi solves this in < 0.1 s.

    _future_s = list(range(1, L + 1))            # state stages 1 … L

    m.lo1       = pyo.Var(states, domain=pyo.Binary)
    m.lo2       = pyo.Var(states, domain=pyo.Binary)
    m.lo1[0].fix(float(state['low_override_r1']))
    m.lo2[0].fix(float(state['low_override_r2']))

    m.cold_r1     = pyo.Var(_future_s, domain=pyo.Binary)
    m.cold_r2     = pyo.Var(_future_s, domain=pyo.Binary)
    m.not_warm_r1 = pyo.Var(_future_s, domain=pyo.Binary)
    m.not_warm_r2 = pyo.Var(_future_s, domain=pyo.Binary)
    m.bc_r1       = pyo.Var(_future_s, domain=pyo.Binary)
    m.bc_r2       = pyo.Var(_future_s, domain=pyo.Binary)

    if L > 1:
        m.hum_hi = pyo.Var(list(range(1, L)), domain=pyo.Binary)

    # ── Fix initial state (τ = 0) ─────────────────────────────────────
    m.T1[0].fix(float(state['T1']))
    m.T2[0].fix(float(state['T2']))
    m.H[0].fix(float(state['H']))
    m.vc[0].fix(float(state['vent_counter']))

    # ── Dynamics constraints:  state[τ+1] = f(state[τ], action[τ]) ───
    m.dyn = pyo.ConstraintList()

    for tau in stages:
        occ1_tau = exp_occ1[tau]
        occ2_tau = exp_occ2[tau]

        # T1[τ+1] = T1[τ] + a(T2[τ]-T1[τ]) + b(T_out-T1[τ]) + g·p1[τ] - c·v[τ] + e·occ1
        m.dyn.add(
            m.T1[tau+1] == m.T1[tau]
            + a_ex * (m.T2[tau] - m.T1[tau])
            + b_tl * (T_out[tau] - m.T1[tau])
            + g_he * m.p1[tau]
            - c_vc * m.v[tau]
            + e_oc * occ1_tau
        )

        # T2[τ+1] = T2[τ] + a(T1[τ]-T2[τ]) + b(T_out-T2[τ]) + g·p2[τ] - c·v[τ] + e·occ2
        m.dyn.add(
            m.T2[tau+1] == m.T2[tau]
            + a_ex * (m.T1[tau] - m.T2[tau])
            + b_tl * (T_out[tau] - m.T2[tau])
            + g_he * m.p2[tau]
            - c_vc * m.v[tau]
            + e_oc * occ2_tau
        )

        # H[τ+1] = H[τ] + eh·(occ1+occ2) - hv·v[τ]
        m.dyn.add(
            m.H[tau+1] == m.H[tau]
            + eh * (occ1_tau + occ2_tau)
            - hv * m.v[tau]
        )

        # vc[τ+1] = (vc[τ] + 1) · v[τ]
        #         = w[τ] + v[τ]      where w[τ] = vc[τ] · v[τ]
        #
        # McCormick envelope for w[τ] = vc[τ] · v[τ]:
        #   v[τ] ∈ {0,1} so this simplifies to:
        #     w[τ] ≤ vc[τ]
        #     w[τ] ≤ T_SLOTS · v[τ]
        #     w[τ] ≥ vc[τ] - T_SLOTS · (1 - v[τ])
        #     w[τ] ≥ 0
        M_vc = float(T_SLOTS)
        m.dyn.add(m.w[tau] <= m.vc[tau])
        m.dyn.add(m.w[tau] <= M_vc * m.v[tau])
        m.dyn.add(m.w[tau] >= m.vc[tau] - M_vc * (1.0 - m.v[tau]))
        # w[τ] ≥ 0 is already in the variable bounds

        m.dyn.add(m.vc[tau+1] == m.w[tau] + m.v[tau])

    # ── Overrule / feasibility constraints at each stage ──────────────
    m.overrule = pyo.ConstraintList()

    # Stage τ=0: use the OBSERVED state for overrule logic
    vc_obs   = int(state['vent_counter'])
    H_obs    = float(state['H'])
    T1_obs   = float(state['T1'])
    T2_obs   = float(state['T2'])
    lo_r1    = int(state['low_override_r1'])
    lo_r2    = int(state['low_override_r2'])

    # Ventilation overrules at τ=0
    if H_obs > d['humidity_threshold']:
        m.overrule.add(m.v[0] == 1)
    if 0 < vc_obs < U_V:
        m.overrule.add(m.v[0] == 1)

    # Heater overrules at τ=0
    if T1_obs > d['temp_max_comfort_threshold']:
        m.overrule.add(m.p1[0] == 0.0)
    elif lo_r1 == 1:
        m.overrule.add(m.p1[0] == P_MAX)

    if T2_obs > d['temp_max_comfort_threshold']:
        m.overrule.add(m.p2[0] == 0.0)
    elif lo_r2 == 1:
        m.overrule.add(m.p2[0] == P_MAX)

    # Stages τ=1,…,L-1: ventilation minimum-uptime constraint
    # If vent was on at τ and counter < U_V, it must stay on at τ+1.
    # We enforce this with:  v[τ+1] ≥ v[τ]  when vc[τ+1] could be < U_V
    #
    # More precisely: if v[τ]=1 and vc[τ+1] < U_V, then v[τ+1]=1.
    # Linearised:  v[τ+1] ≥ v[τ] − (1/U_V)·vc[τ]
    # (When vc[τ] ≥ U_V−1 and v[τ]=1, vc[τ+1]=vc[τ]+1 ≥ U_V → free to stop.)
    #
    # We use a simpler but slightly tighter formulation:
    # For each consecutive pair, if vent starts at some τ, it must stay
    # on for U_V consecutive stages.  We enforce:
    #   v[τ] − v[τ-1_eff] ≤ v[τ+j]  for j = 1, …, min(U_V-1, L-1-τ)
    # where v[τ-1_eff] represents whether vent was on before τ.
    #
    # For τ=0:  v_prev = 1 if vc_obs > 0, else 0
    # For τ>0:  v_prev = v[τ-1]

    # "start indicator":  s[τ] = 1  iff ventilation switches from OFF to ON at τ
    m.s = pyo.Var(stages, domain=pyo.Binary)
    m.start_con = pyo.ConstraintList()

    v_prev_0 = 1 if vc_obs > 0 else 0
    # s[0] linearisation
    m.start_con.add(m.s[0] >= m.v[0] - v_prev_0)
    m.start_con.add(m.s[0] <= m.v[0])
    m.start_con.add(m.s[0] <= 1 - v_prev_0)

    for tau in range(1, L):
        m.start_con.add(m.s[tau] >= m.v[tau] - m.v[tau-1])
        m.start_con.add(m.s[tau] <= m.v[tau])
        m.start_con.add(m.s[tau] <= 1 - m.v[tau-1])

    # If vent starts at τ, it must stay on for U_V consecutive stages
    for tau in stages:
        for j in range(1, U_V):
            if tau + j < L:
                m.start_con.add(m.v[tau+j] >= m.s[tau])

    # If vent was already running at entry and hasn't reached U_V yet,
    # force it to stay on for the remaining time
    if 0 < vc_obs < U_V:
        remaining = U_V - vc_obs
        for j in range(min(remaining, L)):
            m.overrule.add(m.v[j] == 1)

    # ── Overrule tracking at future stages (τ ≥ 1) ───────────────────
    #
    #  For each state stage τ = 1 … L, track the low-override flag:
    #
    #    lo_r(τ) = 1  iff  T_r(τ) ≤ T_LOW             [cold trigger]
    #                  OR  (lo_r(τ-1)=1 AND T_r(τ) < T_OK) [hysteresis]
    #
    #  Enforcement at decision stages τ = 1 … L−1:
    #    lo_r(τ) = 1  →  p_r(τ) = P_MAX
    #    H(τ) > H_THR →  v(τ) = 1

    T_OK   = float(d['temp_OK_threshold'])     # 22 °C
    H_THR  = float(d['humidity_threshold'])    # 70 %
    M_T    = 25.0     # big-M for temperature range (~5–40 °C)
    M_H    = 150.0    # big-M for humidity range   (~0–200 %)
    _DELTA = 0.001    # offset so cold indicator activates at T ≤ T_LOW

    m.or_track = pyo.ConstraintList()

    for tau in range(1, L + 1):
        # ── cold_r(τ) ≡ [T_r(τ) ≤ T_LOW] ──────────────────────────
        #  cold=0 → T > T_LOW :  T ≥ T_LOW + δ − M·cold
        #  cold=1 → T ≤ T_LOW :  T ≤ T_LOW + M·(1−cold)
        m.or_track.add(m.T1[tau] >= T_LOW + _DELTA - M_T * m.cold_r1[tau])
        m.or_track.add(m.T1[tau] <= T_LOW + M_T * (1 - m.cold_r1[tau]))
        m.or_track.add(m.T2[tau] >= T_LOW + _DELTA - M_T * m.cold_r2[tau])
        m.or_track.add(m.T2[tau] <= T_LOW + M_T * (1 - m.cold_r2[tau]))

        # ── not_warm_r(τ) ≡ [T_r(τ) < T_OK] ───────────────────────
        #  nw=0 → T ≥ T_OK :  T ≥ T_OK − M·nw
        #  nw=1 → T < T_OK :  T ≤ T_OK + M·(1−nw)
        m.or_track.add(m.T1[tau] >= T_OK - M_T * m.not_warm_r1[tau])
        m.or_track.add(m.T1[tau] <= T_OK + M_T * (1 - m.not_warm_r1[tau]))
        m.or_track.add(m.T2[tau] >= T_OK - M_T * m.not_warm_r2[tau])
        m.or_track.add(m.T2[tau] <= T_OK + M_T * (1 - m.not_warm_r2[tau]))

        # ── bc_r(τ) = AND(lo_prev, not_warm_r(τ)) ──────────────────
        m.or_track.add(m.bc_r1[tau] <= m.lo1[tau - 1])
        m.or_track.add(m.bc_r1[tau] <= m.not_warm_r1[tau])
        m.or_track.add(m.bc_r1[tau] >= m.lo1[tau - 1] + m.not_warm_r1[tau] - 1)
        m.or_track.add(m.bc_r2[tau] <= m.lo2[tau - 1])
        m.or_track.add(m.bc_r2[tau] <= m.not_warm_r2[tau])
        m.or_track.add(m.bc_r2[tau] >= m.lo2[tau - 1] + m.not_warm_r2[tau] - 1)

        # ── lo_r(τ) = OR(cold_r(τ), bc_r(τ)) ──────────────────────
        m.or_track.add(m.lo1[tau] >= m.cold_r1[tau])
        m.or_track.add(m.lo1[tau] >= m.bc_r1[tau])
        m.or_track.add(m.lo1[tau] <= m.cold_r1[tau] + m.bc_r1[tau])
        m.or_track.add(m.lo2[tau] >= m.cold_r2[tau])
        m.or_track.add(m.lo2[tau] >= m.bc_r2[tau])
        m.or_track.add(m.lo2[tau] <= m.cold_r2[tau] + m.bc_r2[tau])

    # ── Enforcement at future decision stages τ = 1, …, L−1 ────────
    for tau in range(1, L):
        # Heating low override:  lo_r(τ)=1 → p_r(τ) = P_MAX
        m.or_track.add(m.p1[tau] >= P_MAX * m.lo1[tau])
        m.or_track.add(m.p2[tau] >= P_MAX * m.lo2[tau])

        # Humidity overrule:  H(τ) > H_THR → v(τ) = 1
        # hum_hi(τ)=1 when H(τ) exceeds threshold (optimizer prefers 0)
        m.or_track.add(m.H[tau] - H_THR <= M_H * m.hum_hi[tau])
        m.or_track.add(m.v[tau] >= m.hum_hi[tau])

    # ── Terminal VFA:  θ_{t+L}ᵀ φ(s̃_{t+L}) ─────────────────────────
    #
    # We need the VFA weights at time t0+L.  If t0+L ≥ T_SLOTS, the
    # terminal value is 0 (no future costs beyond the horizon).

    t_terminal = t0 + L
    if t_terminal >= T_SLOTS:
        theta_term = np.zeros(N_FEATURES)
    else:
        theta_term = theta_list[t_terminal]

    th = theta_term

    # The terminal VFA is:  th ᵀ φ(s_{t+L})
    # Most features of s_{t+L} are encoded in state variables m.T1[L],
    # m.T2[L], m.H[L], m.vc[L], plus constants for price/occ/time.

    # Construct the VFA expression feature by feature:
    #   φ_0  = 1                                  (constant)
    #   φ_1  = T1[L] / 25                         (variable)
    #   φ_2  = T2[L] / 25                         (variable)
    #   φ_3  = H[L]  / 50                         (variable)
    #   φ_4  = E[λ_{t+L}] / 6                     (constant)
    #   φ_5  = E[λ_{t+L-1}] / 6                   (constant — prev price at t+L)
    #   φ_6  = E[κ1_{t+L}] / 35                   (constant)
    #   φ_7  = E[κ2_{t+L}] / 35                   (constant)
    #   φ_8  = (t0+L) / 10                         (constant)
    #   φ_9  = min(vc[L], 3) / 3                  (variable — approx with vc[L]/3, capped)
    #   φ_10 = max(0, T_low − T1[L]) / 5          (piecewise → z1)
    #   φ_11 = max(0, T_low − T2[L]) / 5          (piecewise → z2)

    # For φ_9: we approximate min(vc[L],3)/3 ≈ vc[L]/3 since vc[L] ≤ L+vc_obs
    # and L is small (3).  For a tighter formulation we cap it, but since
    # vc[L] ≤ L + vc_obs and L=3, this is at most ~6/3 = 2, which is close
    # enough for the VFA's purposes.  We use an auxiliary variable for the cap.
    m.vc_cap = pyo.Var(domain=pyo.NonNegativeReals, bounds=(0.0, 3.0))
    m.vc_cap_c1 = pyo.Constraint(expr = m.vc_cap <= m.vc[L])
    m.vc_cap_c2 = pyo.Constraint(expr = m.vc_cap <= 3.0)
    # To ensure vc_cap = min(vc[L], 3), since θ_9 can be positive or negative,
    # we also need: vc_cap ≥ vc[L] - M*(indicator that vc[L]>3).
    # For simplicity and since vc[L] ≤ L+vc_obs ≤ ~13 at most, we add:
    m.vc_cap_bin = pyo.Var(domain=pyo.Binary)  # 1 if vc[L] > 3
    M_vc_cap = float(T_SLOTS)
    m.vc_cap_c3 = pyo.Constraint(expr = m.vc[L] <= 3.0 + M_vc_cap * m.vc_cap_bin)
    m.vc_cap_c4 = pyo.Constraint(expr = m.vc_cap >= m.vc[L] - M_vc_cap * m.vc_cap_bin)
    m.vc_cap_c5 = pyo.Constraint(expr = m.vc_cap >= 3.0 * m.vc_cap_bin)

    # Constant parts of the VFA
    vfa_const = (
        th[0]  * 1.0
      + th[4]  * exp_price[L]     / 6.0
      + th[5]  * exp_price[L-1]   / 6.0      # prev price at terminal = price at L-1
      + th[6]  * exp_occ1[L]      / 35.0
      + th[7]  * exp_occ2[L]      / 35.0
      + th[8]  * t_terminal       / float(T_SLOTS)
    )

    # Full VFA expression (mixed constant + variable)
    def vfa_terminal(m):
        return (
            vfa_const
          + th[1]  * m.T1[L]    / 25.0
          + th[2]  * m.T2[L]    / 25.0
          + th[3]  * m.H[L]     / 50.0
          + th[9]  * m.vc_cap   / 3.0
          + th[10] * m.z1
          + th[11] * m.z2
        )

    # z1, z2 constraints for terminal cold-risk features
    m.z1_nonneg = pyo.Constraint(expr = m.z1 >= 0.0)
    m.z1_cold   = pyo.Constraint(expr = m.z1 >= (T_LOW - m.T1[L]) / 5.0)
    m.z2_nonneg = pyo.Constraint(expr = m.z2 >= 0.0)
    m.z2_cold   = pyo.Constraint(expr = m.z2 >= (T_LOW - m.T2[L]) / 5.0)

    # ── Objective: sum of stage costs + terminal VFA ──────────────────
    #
    #   min  Σ_{τ=0}^{L-1}  λ_{t+τ} · (p1[τ] + p2[τ] + P_vent · v[τ])
    #        + θ_{t+L}ᵀ φ(s̃_{t+L})

    def obj_rule(m):
        stage_costs = sum(
            exp_price[tau] * (m.p1[tau] + m.p2[tau] + P_V * m.v[tau])
            for tau in stages
        )
        return stage_costs + vfa_terminal(m)

    m.obj = pyo.Objective(rule=obj_rule, sense=pyo.minimize)

    # ── Solve ─────────────────────────────────────────────────────────
    solver = _get_solver()
    result = solver.solve(m, tee=False)

    ok = (result.solver.termination_condition == pyo.TerminationCondition.optimal)

    if not ok:
        # Fallback: try the 1-step MILP, then greedy
        try:
            theta_next = theta_list[t0 + 1] if t0 + 1 < T_SLOTS \
                         else np.zeros(N_FEATURES)
            return _solve_1step_MILP(state, theta_next)
        except Exception:
            return _greedy_action(state)

    # Extract HERE-AND-NOW decision (τ=0 only)
    return {
        'HeatPowerRoom1': float(np.clip(pyo.value(m.p1[0]), 0.0, P_MAX)),
        'HeatPowerRoom2': float(np.clip(pyo.value(m.p2[0]), 0.0, P_MAX)),
        'VentilationON':  int(round(float(pyo.value(m.v[0])))),
    }


# ═══════════════════════════════════════════════════════════════════════
# SECTION 7 — LOAD PRE-TRAINED WEIGHTS FROM CSV
# ═══════════════════════════════════════════════════════════════════════
#
#  Weights are trained OFFLINE by the separate script `train_adp_weights.py`
#  (N=2000 scenarios, K=5 iterations, L=10 lookahead) and saved to a CSV
#  file with shape (T_SLOTS, N_FEATURES) = (10, 12).
#
#  This avoids any training overhead at evaluation time — the policy just
#  loads the CSV and immediately starts solving deployment MILPs.

_WEIGHTS_CSV = os.path.join(_DIR, 'adp_weights_20.csv')

if os.path.exists(_WEIGHTS_CSV):
    _theta_matrix = np.loadtxt(_WEIGHTS_CSV, delimiter=',', skiprows=0)
    assert _theta_matrix.shape == (T_SLOTS, N_FEATURES), \
        f"Weight CSV shape mismatch: expected ({T_SLOTS},{N_FEATURES}), got {_theta_matrix.shape}"
    _THETA_LIST = [_theta_matrix[t] for t in range(T_SLOTS)]
    print(f"[ADP-MS] Loaded pre-trained weights from {_WEIGHTS_CSV}")
else:
    # Fallback: train on the fly (slow, for development only)
    print(f"[ADP-MS] WARNING: {_WEIGHTS_CSV} not found. Training from scratch…")
    _THETA_LIST = train_ADP(n_scenarios=N_SCENARIOS, n_iter=N_ITER, verbose=True)
    # Save for next time
    np.savetxt(_WEIGHTS_CSV, np.array(_THETA_LIST), delimiter=',')
    print(f"[ADP-MS] Saved weights to {_WEIGHTS_CSV}")


# ═══════════════════════════════════════════════════════════════════════
# SECTION 8 — POLICY ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════

def select_action(state):
    """
    Multi-stage ADP policy.

    At each hour t, solve an L-step lookahead MILP that:
      1. Optimises decisions explicitly over L stages
      2. Uses expected prices and occupancies as certainty equivalents
      3. Attaches the learned VFA θ_{t+L}ᵀφ(s̃_{t+L}) as terminal value

    Only the here-and-now decision (τ=0) is returned and executed.
    The remaining L-1 decisions are discarded (rolling horizon).

    Parameters
    ----------
    state : dict — current environment state

    Returns
    -------
    dict with keys  HeatPowerRoom1, HeatPowerRoom2, VentilationON
    """
    t = int(state['current_time'])

    # Adapt lookahead to remaining horizon
    remaining = T_SLOTS - t
    L = min(LOOKAHEAD_STEPS, remaining)

    if L <= 0:
        # No decisions left
        return {'HeatPowerRoom1': 0.0, 'HeatPowerRoom2': 0.0, 'VentilationON': 0}

    if L == 1:
        # Fall back to 1-step MILP (identical to v1)
        theta_next = _THETA_LIST[t + 1] if t + 1 < T_SLOTS \
                     else np.zeros(N_FEATURES)
        return _solve_1step_MILP(state, theta_next)

    return _solve_multistage_MILP(state, _THETA_LIST, L)
